### ISSUE TITLE
List this parser at nvim-treesitter?

### ISSUE THREAD

**Issue by theHamsta** [szebniok/tree-sitter-wgsl#1]
I asking whether you are interested in listing your parser at nvim-treesitter/nvim-treesitter. It would give the language more visibility. We could also just add the install info to plugin with a link to this repo or import the queries directly from that repo when the fit with their captures to the other languages.

**Comment by szebniok** [comment]
Hey @theHamsta, thank you for reaching out to me. I'm definitely interested.
I have to admit, this parser got a bit out of sync with the current wgsl spec, but I should be able to get it up to date till Tuesday (05.04).
How should I proceed afterwards? Should I open up a PR that adds the queries and an appropriate entry inside the `lua/nvim-treesitter/parsers.lua` file (similarly to the recently merged YANG https://github.com/nvim-treesitter/nvim-treesitter/pull/1593 and elvish https://github.com/nvim-treesitter/nvim-treesitter/pull/2681 PRs)?

**Comment by theHamsta** [comment]
Yes, that would be ideal! Thank you for your response!

**Comment by szebniok** [comment]
Hey, sorry for being late. I've severely underestimated the amount of WGSL's spec changes that happened during the past 7 months :D.

Here is the PR: https://github.com/nvim-treesitter/nvim-treesitter/pull/2771
